# Nixpacks configuration for Railway
# Tells Railway where the Node.js app is located

[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["cd backend && npm install --production"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "cd backend && node src/server.js"
